services:
  mongo: # name of the service
    image: mongo # Runs this image, as foldername/nameoftheservice
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # sets up db
      - ./mongo_data:/data/db # persists the data
    container_name: mongodb
  redis:
    image: redis:8.2-alpine
    ports:
      - 7890:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD, to persist the data
    volumes:
      - ./redis_data:/data
  backend-dev:
    image: backend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: backend-dev # This will name the container

